# EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)

### Name: HONRADO, John Clark D.
### Section: 2ECE-A
### September 1, 2024

### --------------------------------------------------------------------------------------------

## NORMALIZATION PROBLEM

In [1]:
# Using the Numpy library
import numpy as np

# Create a random 5 x 5 ndarray and store it to variable X
X = np.random.random((5, 5))

# Normalize X using .mean() and .std() calls
X_normalized = (X - X.mean()) / (X.std())

# Save your normalized ndarray as X_normalized.npy
np.save('X_normalized.npy', X_normalized)

# Testing
print("Random 5 x 5 ndarray:\n\n", X)
print("\n\nElement-wise mean: ", X.mean())
print("Element-wise standard deviation:", X.std())
print("\n\nNormalized values of X:\n\n", np.load('X_normalized.npy'))

Random 5 x 5 ndarray:

 [[0.69149249 0.55014892 0.39413861 0.22531954 0.25852837]
 [0.0662937  0.89881911 0.45406716 0.608238   0.0751138 ]
 [0.86318263 0.85679701 0.33198891 0.58767438 0.73341879]
 [0.7679534  0.42899107 0.04286228 0.25751901 0.25236955]
 [0.3207652  0.05373915 0.07104778 0.93924756 0.06703717]]


Element-wise mean:  0.43187014444949745
Element-wise standard deviation: 0.2939949692477308


Normalized values of X:

 [[ 0.88308431  0.40231566 -0.12834074 -0.70256511 -0.58960796]
 [-1.24347859  1.58828897  0.07550134  0.59990094 -1.21347772]
 [ 1.46707438  1.44535421 -0.33973789  0.52995544  1.02569322]
 [ 1.1431599  -0.00979294 -1.32317864 -0.5930412  -0.61055667]
 [-0.37791443 -1.28618185 -1.22730794  1.72580305 -1.24094973]]


## DIVISIBLE BY 3 PROBLEM

In [2]:
# Using the Numpy library
import numpy as np

# Creating 10x10 ndarray with squares of first 100 positive integers
Arr = np.array(range(1,101)).reshape(10,10)**2

# Determine all the elements that are divisible by 3.
div_by_3 = Arr[Arr % 3 == 0]

# Save the result as div_by_3.npy
np.save('div_by_3.npy', div_by_3)

# Testing
print("10x10 ndarray with squares of first 100 positive integers: \n\n", Arr)
print("\n\nElements that are divisible by 3:\n\n", np.load('div_by_3.npy'))

10x10 ndarray with squares of first 100 positive integers: 

 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


Elements that are divisible by 3:

 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
